[build]
  command = "npm install"
  publish = "."

[build.environment]
  SECRETS_SCAN_ENABLED = "true"

[functions]
  included_files = ["skills/**", "skills.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
